name: "Build Android App"
on: 
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Java 
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: "adopt"
          cache: "gradle"

      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: '23'

      - name: Run NPM Install
        run: | 
              npx expo prebuild -p android
              npm install

      - name: Change wrapper permissions
        run: chmod +x ./android/gradlew

      - name: Build App
        run: |
              cd ./android
              ./gradlew assembleRelease

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with: 
            name: app
            path: ./android/app/build/outputs/apk/release/app-release.apk
            retention-days: 3